### ISSUE TITLE
What exactly are the tokens for?

### ISSUE THREAD

**Issue by SirWindfield** [bytesnake/hex#19]
From an implementation point of view, what do they actually do? Looks like they act as some kind of struct to refer to albums. But I'm not sure.

**Comment by bytesnake** [comment]
Clarified in 8adc59fcce746b61ba149bec5e5d75850e88a4b6.
You can see one here, but we're still experimenting how they're looking like:
![photo_2018-10-12_12-05-06](https://user-images.githubusercontent.com/989353/46863217-182d6d00-ce17-11e8-9fac-29d520ed3c10.jpg)
](url)

**Comment by SirWindfield** [comment]
What a great idea :)
