### ISSUE TITLE
Does hex support more than just opus?

### ISSUE THREAD

**Issue by SirWindfield** [bytesnake/hex#20]
Would hex be able to read and play mp3 files or aac files?

**Comment by bytesnake** [comment]
Probably not, clarified in 8adc59fcce746b61ba149bec5e5d75850e88a4b6.
Greetings from Aachen!

**Comment by SirWindfield** [comment]
Not sure how I missed that part. Thanks you! I was actually working on a super similar project the past week. Written in Rust too. A music library/player that supports plugins. But it looks like you outpaced me :)
